-- ============================================================
-- KIEM TRA DU LIEU SAU KHI IMPORT SEED
-- Chi gom SELECT, khong sua du lieu.
-- ============================================================

ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

-- 1. Object invalid sau khi import.
SELECT object_type, object_name, status
FROM user_objects
WHERE object_type IN ('TRIGGER', 'FUNCTION', 'PROCEDURE', 'VIEW')
  AND status <> 'VALID'
ORDER BY object_type, object_name;

-- 2. So dong cac bang nghiep vu chinh.
SELECT 'VAITRO' bang, COUNT(*) so_dong FROM VAITRO
UNION ALL SELECT 'TAIKHOAN', COUNT(*) FROM TAIKHOAN
UNION ALL SELECT 'NHANVIEN', COUNT(*) FROM NHANVIEN
UNION ALL SELECT 'NANGLUCNHANVIEN', COUNT(*) FROM NANGLUCNHANVIEN
UNION ALL SELECT 'HOCHIEUSO', COUNT(*) FROM HOCHIEUSO
UNION ALL SELECT 'TOURMAU', COUNT(*) FROM TOURMAU
UNION ALL SELECT 'LICHTRINHTOUR', COUNT(*) FROM LICHTRINHTOUR
UNION ALL SELECT 'TOURTHUCTE', COUNT(*) FROM TOURTHUCTE
UNION ALL SELECT 'DONDATTOUR', COUNT(*) FROM DONDATTOUR
UNION ALL SELECT 'CHITIETDATTOUR', COUNT(*) FROM CHITIETDATTOUR
UNION ALL SELECT 'DSNGUOIDONGHANH', COUNT(*) FROM DSNGUOIDONGHANH
UNION ALL SELECT 'GIAODICH', COUNT(*) FROM GIAODICH
UNION ALL SELECT 'CHIPHITHUCTE', COUNT(*) FROM CHIPHITHUCTE
UNION ALL SELECT 'QUYETTOAN', COUNT(*) FROM QUYETTOAN;

-- 3. Kiem tra cac quan he cha-con co nguy co mo coi.
SELECT 'TAIKHOAN.VAITRO -> VAITRO' kiem_tra, COUNT(*) so_loi
FROM TAIKHOAN tk
WHERE NOT EXISTS (SELECT 1 FROM VAITRO vt WHERE vt.MaVaiTro = tk.VaiTro)
UNION ALL
SELECT 'NHANVIEN.MaTaiKhoan -> TAIKHOAN', COUNT(*)
FROM NHANVIEN nv
WHERE NOT EXISTS (SELECT 1 FROM TAIKHOAN tk WHERE tk.MaTaiKhoan = nv.MaTaiKhoan)
UNION ALL
SELECT 'HOCHIEUSO.MaTaiKhoan -> TAIKHOAN', COUNT(*)
FROM HOCHIEUSO hcs
WHERE NOT EXISTS (SELECT 1 FROM TAIKHOAN tk WHERE tk.MaTaiKhoan = hcs.MaTaiKhoan)
UNION ALL
SELECT 'NANGLUCNHANVIEN.MaNhanVien -> NHANVIEN', COUNT(*)
FROM NANGLUCNHANVIEN nl
WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN nv WHERE nv.MaNhanVien = nl.MaNhanVien)
UNION ALL
SELECT 'LICHTRINHTOUR.MaTourMau -> TOURMAU', COUNT(*)
FROM LICHTRINHTOUR lt
WHERE NOT EXISTS (SELECT 1 FROM TOURMAU tm WHERE tm.MaTourMau = lt.MaTourMau)
UNION ALL
SELECT 'TOURTHUCTE.MaTourMau -> TOURMAU', COUNT(*)
FROM TOURTHUCTE ttt
WHERE NOT EXISTS (SELECT 1 FROM TOURMAU tm WHERE tm.MaTourMau = ttt.MaTourMau)
UNION ALL
SELECT 'PHANCONGTOUR.MaTourThucTe -> TOURTHUCTE', COUNT(*)
FROM PHANCONGTOUR pct
WHERE NOT EXISTS (SELECT 1 FROM TOURTHUCTE ttt WHERE ttt.MaTourThucTe = pct.MaTourThucTe)
UNION ALL
SELECT 'PHANCONGTOUR.MaNhanVien -> NHANVIEN', COUNT(*)
FROM PHANCONGTOUR pct
WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN nv WHERE nv.MaNhanVien = pct.MaNhanVien)
UNION ALL
SELECT 'DONDATTOUR.MaTourThucTe -> TOURTHUCTE', COUNT(*)
FROM DONDATTOUR ddt
WHERE NOT EXISTS (SELECT 1 FROM TOURTHUCTE ttt WHERE ttt.MaTourThucTe = ddt.MaTourThucTe)
UNION ALL
SELECT 'DONDATTOUR.MaKhachHang -> HOCHIEUSO', COUNT(*)
FROM DONDATTOUR ddt
WHERE NOT EXISTS (SELECT 1 FROM HOCHIEUSO hcs WHERE hcs.MaKhachHang = ddt.MaKhachHang)
UNION ALL
SELECT 'DSNGUOIDONGHANH.MaDatTour -> DONDATTOUR', COUNT(*)
FROM DSNGUOIDONGHANH ndh
WHERE NOT EXISTS (SELECT 1 FROM DONDATTOUR ddt WHERE ddt.MaDatTour = ndh.MaDatTour)
UNION ALL
SELECT 'CHITIETDATTOUR.MaDatTour -> DONDATTOUR', COUNT(*)
FROM CHITIETDATTOUR ctdt
WHERE NOT EXISTS (SELECT 1 FROM DONDATTOUR ddt WHERE ddt.MaDatTour = ctdt.MaDatTour)
UNION ALL
SELECT 'CHITIETDATTOUR.MaKhachHang -> HOCHIEUSO', COUNT(*)
FROM CHITIETDATTOUR ctdt
WHERE ctdt.MaKhachHang IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM HOCHIEUSO hcs WHERE hcs.MaKhachHang = ctdt.MaKhachHang)
UNION ALL
SELECT 'CHITIETDATTOUR.MaNguoiDongHanh -> DSNGUOIDONGHANH', COUNT(*)
FROM CHITIETDATTOUR ctdt
WHERE ctdt.MaNguoiDongHanh IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM DSNGUOIDONGHANH ndh WHERE ndh.MaNguoiDongHanh = ctdt.MaNguoiDongHanh)
UNION ALL
SELECT 'GIAODICH.MaDatTour -> DONDATTOUR', COUNT(*)
FROM GIAODICH gd
WHERE NOT EXISTS (SELECT 1 FROM DONDATTOUR ddt WHERE ddt.MaDatTour = gd.MaDatTour)
UNION ALL
SELECT 'CHIPHITHUCTE.MaTourThucTe -> TOURTHUCTE', COUNT(*)
FROM CHIPHITHUCTE cp
WHERE NOT EXISTS (SELECT 1 FROM TOURTHUCTE ttt WHERE ttt.MaTourThucTe = cp.MaTourThucTe)
UNION ALL
SELECT 'CHIPHITHUCTE.MaNhanVien -> NHANVIEN', COUNT(*)
FROM CHIPHITHUCTE cp
WHERE NOT EXISTS (SELECT 1 FROM NHANVIEN nv WHERE nv.MaNhanVien = cp.MaNhanVien)
UNION ALL
SELECT 'QUYETTOAN.MaTourThucTe -> TOURTHUCTE', COUNT(*)
FROM QUYETTOAN qt
WHERE NOT EXISTS (SELECT 1 FROM TOURTHUCTE ttt WHERE ttt.MaTourThucTe = qt.MaTourThucTe);

-- 4. Kiem tra cac bat nhat nghiep vu hay gap sau seed.
SELECT t.MaTourThucTe, t.TrangThai, COUNT(p.MaPhanCongTour) so_hdv_dong_y
FROM TOURTHUCTE t
LEFT JOIN PHANCONGTOUR p
  ON p.MaTourThucTe = t.MaTourThucTe
 AND p.TrangThaiChapNhan = 'DA_DONG_Y'
WHERE t.TrangThai = 'MO_BAN'
GROUP BY t.MaTourThucTe, t.TrangThai
HAVING COUNT(p.MaPhanCongTour) = 0
ORDER BY t.MaTourThucTe;

SELECT t.MaTourThucTe, t.SoKhachToiDa, t.ChoConLai,
       COUNT(c.MaChiTietDat) so_khach_hieu_luc,
       t.SoKhachToiDa - COUNT(c.MaChiTietDat) cho_con_lai_dung
FROM TOURTHUCTE t
LEFT JOIN DONDATTOUR d
  ON d.MaTourThucTe = t.MaTourThucTe
 AND d.TrangThai IN ('CHO_XAC_NHAN', 'DA_XAC_NHAN')
LEFT JOIN CHITIETDATTOUR c ON c.MaDatTour = d.MaDatTour
GROUP BY t.MaTourThucTe, t.SoKhachToiDa, t.ChoConLai
HAVING t.ChoConLai <> t.SoKhachToiDa - COUNT(c.MaChiTietDat)
ORDER BY t.MaTourThucTe;

