ALTER TABLE YEUCAUHOTRO DROP CONSTRAINT CK_YCHT_TrangThai;

ALTER TABLE YEUCAUHOTRO ADD CONSTRAINT CK_YCHT_TrangThai CHECK (
    TrangThai IN ('CHUA_XU_LY','CHO_BO_SUNG','CHO_GIAI_TRINH','CHO_DUYET','DA_XU_LY','TU_CHOI')
);
